spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.101.132:3306/media_file
    username: root
    password: root
  config:
    import: optional:bootstrap.yml